// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDow4YETfllYF-I4fcwE1y4AFY4fcvhhz8',
    appId: '1:965658095626:web:a52a283fb23eb4d12deff3',
    messagingSenderId: '965658095626',
    projectId: 'bolu-hotel',
    authDomain: 'bolu-hotel.firebaseapp.com',
    storageBucket: 'bolu-hotel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNvG15XvPDsPIFDAJWqp5rcPjsl49Z4Z0',
    appId: '1:965658095626:android:70bd9d6704d7ccee2deff3',
    messagingSenderId: '965658095626',
    projectId: 'bolu-hotel',
    storageBucket: 'bolu-hotel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSX3rKAyzo8_aBz1ZOctalWjF-1wJ-MVI',
    appId: '1:965658095626:ios:5dd63e69227998c22deff3',
    messagingSenderId: '965658095626',
    projectId: 'bolu-hotel',
    storageBucket: 'bolu-hotel.appspot.com',
    iosBundleId: 'com.example.hotelBooking',
  );
}
